### ISSUE TITLE
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading

### ISSUE THREAD

**Issue by madeeldevops** [adeel14553/docker-to-ecr#3]

**Comment by adeel14553** [comment]
After the docker update , the docker hub have throtling for pulling the images, so instead pull images from aws ecr public gallery.

`FROM public.ecr.aws/lambda/nodejs:latest` 

Updated in docker file.

**Comment by madeeldevops** [comment]
Try to create account in docker and login with it, or 
you can just create a docker image from dockerfile and push it manually to ECR locally or in ec2 instance. Once you get the image in ecr you can deploy it ecs fargate.
